# Generated by Django 4.2.5 on 2023-10-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GigaGames', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='rut',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
