# Generated by Django 4.2.5 on 2023-10-01 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GigaGames', '0002_perfil_direccion_perfil_rut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='rut',
        ),
    ]
