# Generated by Django 4.2.5 on 2023-09-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GigaGames', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='imagen_carrusel',
            field=models.ImageField(blank=True, null=True, upload_to='cover/carrusel'),
        ),
    ]
