# Generated by Django 4.2.5 on 2023-10-01 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GigaGames', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra_juego',
            old_name='Juego',
            new_name='juego',
        ),
        migrations.RenameField(
            model_name='juego',
            old_name='Categoria',
            new_name='categoria',
        ),
        migrations.AddField(
            model_name='juego',
            name='imagen_carrusel',
            field=models.ImageField(blank=True, null=True, upload_to='cover/carrusel'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nombre de la categoria'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
