# Generated by Django 4.2.5 on 2023-10-01 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GigaGames', '0003_remove_perfil_nombre_perfil_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra_juego',
            old_name='Juego',
            new_name='juego',
        ),
        migrations.RenameField(
            model_name='juego',
            old_name='Categoria',
            new_name='categoria',
        ),
    ]
