# Generated by Django 4.2.5 on 2023-10-01 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GigaGames', '0004_rename_juego_compra_juego_juego_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='nombre',
        ),
    ]
