# Generated by Django 4.2.5 on 2023-10-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GigaGames', '0005_remove_perfil_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
